USE [master]
GO

/****** Object:  Database [EmailLogDB]    Script Date: 5/21/2024 7:53:40 PM ******/
CREATE DATABASE [EmailLogDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmailLogDB', FILENAME = N'E:\DB\EmailLogDB.mdf' , SIZE = 3940352KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmailLogDB_log', FILENAME = N'F:\DBLOGS\EmailLogDB_log.ldf' , SIZE = 2760704KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmailLogDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmailLogDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EmailLogDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EmailLogDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EmailLogDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EmailLogDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [EmailLogDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EmailLogDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmailLogDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmailLogDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmailLogDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EmailLogDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EmailLogDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmailLogDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EmailLogDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmailLogDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EmailLogDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmailLogDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmailLogDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmailLogDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmailLogDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmailLogDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EmailLogDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmailLogDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EmailLogDB] SET  MULTI_USER 
GO

ALTER DATABASE [EmailLogDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmailLogDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmailLogDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmailLogDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EmailLogDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EmailLogDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EmailLogDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EmailLogDB] SET  READ_WRITE 
GO


